baseURL = 'https://estadistica.tucuman.gov.ar/geoestadistica'
languageCode = 'es-AR'
defaultContentLanguage = "es"
defaultContentLang = "es"
title = 'Portal Geoestadístico'

[markup.goldmark.renderer]
unsafe = true


[menu]
  [[menu.main]]
    name = "Inicio"
    pageref = "/"
    weight=1
  [[menu.main]]
    name = "Visor"
    url="https://estadistica.tucuman.gob.ar/visor/"    
    weight=4
  [[menu.main]]
    name = "Mapoteca"
    pageref = "mapoteca/"
    weight=2
  [[menu.main]]
    name = "Geoservicios"
    pageref = "geoservicios/"
    weight=3
  [[menu.main]]
    name="Visualizadores"
    pageref="visualizadores/"
    weight=5


[taxonomies]
  tag = "tags"
  category = "categories"